services:
  db:
    image: mysql:latest
    container_name: dwtakehome-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}      
      MYSQL_DATABASE: ${DB_NAME}        
      MYSQL_USER: ${DB_USERNAME}             
      MYSQL_PASSWORD: ${DB_PASSWORD}            
    ports:
      - "3306:3306"                        
    volumes:
      - mysql_data:/var/lib/mysql      
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql


  db_mock:
    image: mysql:latest
    container_name: dwtakehome_mock_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME_MOCK}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_mock_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
  db_mock_data:
