version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}          # Root password
      MYSQL_DATABASE: ${DB_NAME}            # Your database name
      MYSQL_USER: ${DB_USERNAME}                # Your MySQL user
      MYSQL_PASSWORD: ${DB_PASSWORD}               # MySQL user password
    ports:
      - "3306:3306"                         # Map host port 3306 to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql           # Persist data between container restarts
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
